### ISSUE TITLE
Metadata duplicated to Image Record

### ISSUE THREAD

**Issue by SimonGruening** [betterFORM/ziziphus#283]
Seemingly all metadata added to the Work Record is also saved in the Image Record. Though the metadata is not shown in the View Mode at first, but only in the Edit Mode. Only after editing they are also visible in the View Mode.

Example - Worktype:
![image](https://cloud.githubusercontent.com/assets/3437957/6782282/69db47b6-d173-11e4-9eae-ca390486949f.png)

And other way round. The Metadata for the Work Record is completely gone and was replaced with the Image Record metadata:
![image](https://cloud.githubusercontent.com/assets/3437957/6782629/8eda05aa-d175-11e4-83a7-8a12654cd892.png)

**Comment by zwobit** [comment]
fixed
